const movies = [
{ name: "Doraemon: Nobita's Dinosaur (1980)" },
  { name: "Doraemon: The Records of Nobita, Spaceblazer (1981)" },
  { name: "Doraemon: Nobita and the Haunts of Evil (1982)" },
  { name: "Doraemon: Nobita and the Castle of the Undersea Devil (1983)" },
  { name: "Doraemon: Nobita's Great Adventure into the Underworld (1984)" },
  { name: "Doraemon: Nobita's Little Star Wars (1985)" },
  { name: "Doraemon: Nobita and the Steel Troops (1986)" },
  { name: "Doraemon: Nobita and the Knights on Dinosaurs (1987)" },
  { name: "Doraemon: The Record of Nobita's Parallel Visit to the West (1988)" },
  { name: "Doraemon: Nobita and the Birth of Japan (1989)" },
  { name: "Doraemon: Nobita and the Animal Planet (1990)" },
  { name: "Doraemon: Nobita's Dorabian Nights (1991)" },
  { name: "Doraemon: Nobita and the Kingdom of Clouds (1992)" },
  { name: "Doraemon: Nobita and the Tin Labyrinth (1993)" },
  { name: "Doraemon: Nobita's Three Visionary Swordsmen (1994)" },
  { name: "Doraemon: Nobita's Diary on the Creation of the World (1995)" },
  { name: "Doraemon: Nobita and the Galaxy Super-express (1996)" },
  { name: "Doraemon: Nobita and the Spiral City (1997)" },
  { name: "Doraemon: Nobita's Great Adventure in the South Seas (1998)" },
  { name: "Doraemon: Nobita Drifts in the Universe (1999)" },
  { name: "Doraemon: Nobita and the Legend of the Sun King (2000)" },
  { name: "Doraemon: Nobita and the Winged Braves (2001)" },
  { name: "Doraemon: Nobita in the Robot Kingdom (2002)" },
  { name: "Doraemon: Nobita and the Windmasters (2003)" },
  { name: "Doraemon: Nobita in the Wan-Nyan Spacetime Odyssey (2004)" },
  { name: "Doraemon: Nobita's Dinosaur 2006 (2006)" },
  { name: "Doraemon: Nobita's New Great Adventure into the Underworld (2007)" },
  { name: "Doraemon: Nobita and the Green Giant Legend (2008)" },
  { name: "Doraemon: The New Record of Nobita's Spaceblazer (2009)" },
  { name: "Doraemon: Nobita's Great Battle of the Mermaid King (2010)" },
  { name: "Doraemon: Nobita and the New Steel Troops—Winged Angels (2011)" },
  { name: "Doraemon: Nobita and the Island of Miracles—Animal Adventure (2012)" },
  { name: "Doraemon: Nobita's Secret Gadget Museum (2013)" },
  { name: "Doraemon: New Nobita's Great Demon—Peko and the Exploration Party of Five (2014)" },
  { name: "Doraemon: Nobita's Space Heroes (2015)" },
  { name: "Doraemon: Nobita and the Birth of Japan 2016 (2016)" },
  { name: "Doraemon: Nobita's Great Adventure in the Antarctic Kachi Kochi (2017)" },
  { name: "Doraemon: Nobita's Treasure Island (2018)" },
  { name: "Doraemon: Nobita's Chronicle of the Moon Exploration (2019)" },
  { name: "Doraemon: Nobita's New Dinosaur (2020)" },
  { name: "Doraemon: Nobita's Little Star Wars 2021 (2022)" },
  { name: "Doraemon: Nobita's Sky Utopia (2023)" },
  { name: "Doraemon: Nobita's Earth Symphony (2024)" },
    { "name": "How to Train Your Dragon (2010)" },
  { "name": "How to Train Your Dragon 2 (2014)" },
  { "name": "How to Train Your Dragon: The Hidden World (2019)" },
  { "name": "Up (2009)" },
  { "name": "Migration" },
  { "name": "Bee Movie (2007)" },
  { "name": "Angry Birds (2016)" },
  { "name": "Angry Birds 2 (2019)" },
  { "name": "The Boss Baby (2017)" }
  ]
